[general]
import = ["~/.config/alacritty/colors.toml"]

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
option_as_alt = "both"

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\n" }
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "open"
post_processing = true
mouse.enabled = true
mouse.mods = "Command"
