[general]
import = ["~/.config/alacritty/colors.toml"]

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
option_as_alt = "both"
